import { useEffect, useMemo, useState } from 'react';
import { Link, useLocation } from 'wouter';
import { Bell, BookOpen, ChevronRight, CircleHelp, Compass, Home, Library, Menu, MessageCircle, PlayCircle, Search, Settings, Sparkles, Target, TrendingUp, X } from 'lucide-react';
import { PRODUCT_NAME, glossary, initials, lessons, readinessScore, roadmapBase, todayLabel, type FinovaState } from '@/lib/finova';

const nav = [
  { href: '/dashboard', label: 'Today', icon: Home },
  { href: '/roadmap', label: 'My roadmap', icon: Compass },
  { href: '/learn', label: 'Learn', icon: BookOpen },
  { href: '/practice', label: 'Practice', icon: PlayCircle },
  { href: '/progress', label: 'Progress', icon: TrendingUp },
];

export function Logo({ light = false }: { light?: boolean }) {
  return <Link href="/" className={`flex items-center gap-2.5 font-semibold tracking-tight ${light ? 'text-[#f6e9cb]' : 'text-[#173b40]'}`} data-testid="link-logo"><span className={`grid h-9 w-9 place-items-center rounded-xl ${light ? 'bg-[#e8bd72] text-[#173b40]' : 'bg-[#1c766e] text-[#f8f1e3]'}`}><Sparkles size={18} /></span><span className="text-lg">{PRODUCT_NAME}</span></Link>;
}

export function AppShell({ children, state }: { children: React.ReactNode; state: FinovaState }) {
  const [location] = useLocation();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [chatOpen, setChatOpen] = useState(false);
  return <div className="app-grain min-h-[100dvh] bg-background">
    <aside className={`fixed inset-y-0 left-0 z-30 w-[248px] bg-sidebar px-5 py-6 text-sidebar-foreground transition-transform md:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex items-center justify-between"><Logo light /><button className="md:hidden" onClick={() => setMobileOpen(false)} aria-label="Close navigation" data-testid="button-close-navigation"><X size={20} /></button></div>
      <div className="mt-10 rounded-2xl border border-sidebar-border bg-sidebar-accent/60 p-4"><p className="text-xs text-sidebar-foreground/65">Your current focus</p><p className="mt-2 font-medium">{roadmapBase.find(x => x.id === state.roadmap.find(id => !state.completedMilestones.includes(id)))?.title || 'Keep learning'}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-sidebar/70"><div className="h-full rounded-full bg-sidebar-primary transition-all" style={{ width: `${Math.round(state.completedMilestones.length / Math.max(1, state.roadmap.length) * 100)}%` }} /></div><p className="mt-2 text-xs text-sidebar-foreground/65">{state.completedMilestones.length} of {state.roadmap.length} milestones complete</p></div>
      <nav className="mt-8 space-y-1" aria-label="Main navigation">{nav.map(item => { const Icon = item.icon; const active = location === item.href; return <Link key={item.href} href={item.href} onClick={() => setMobileOpen(false)} className={`flex items-center gap-3 rounded-xl px-3.5 py-3 text-sm transition-colors ${active ? 'bg-sidebar-primary text-sidebar-primary-foreground font-semibold' : 'text-sidebar-foreground/72 hover:bg-sidebar-accent hover:text-sidebar-foreground'}`} data-testid={`link-nav-${item.label.toLowerCase().replaceAll(' ', '-')}`}><Icon size={18} /><span>{item.label}</span>{active && <ChevronRight size={15} className="ml-auto" />}</Link>})}</nav>
      <div className="absolute bottom-6 left-5 right-5 space-y-1"><Link href="/glossary" className="flex items-center gap-3 rounded-xl px-3.5 py-3 text-sm text-sidebar-foreground/72 hover:bg-sidebar-accent" data-testid="link-glossary"><CircleHelp size={18} />Glossary</Link><Link href="/profile" className="flex items-center gap-3 rounded-xl px-3.5 py-3 text-sm text-sidebar-foreground/72 hover:bg-sidebar-accent" data-testid="link-profile"><Settings size={18} />Profile & settings</Link></div>
    </aside>
    {mobileOpen && <button className="fixed inset-0 z-20 bg-[#173b40]/30 md:hidden" onClick={() => setMobileOpen(false)} aria-label="Close menu overlay" />}
    <main className="md:pl-[248px]"><header className="sticky top-0 z-20 flex h-[72px] items-center justify-between border-b border-border/70 bg-background/90 px-4 backdrop-blur-md sm:px-8"><button className="rounded-lg p-2 md:hidden" onClick={() => setMobileOpen(true)} aria-label="Open navigation" data-testid="button-open-navigation"><Menu size={21} /></button><div className="hidden md:block"><p className="text-sm text-muted-foreground">{todayLabel()}</p><p className="font-medium">A little progress counts today.</p></div><div className="ml-auto flex items-center gap-2"><button className="flex items-center gap-2 rounded-xl border border-border bg-card px-3 py-2 text-sm text-muted-foreground hover:bg-muted" onClick={() => setSearchOpen(true)} data-testid="button-global-search"><Search size={16} /><span className="hidden sm:inline">Search Finova</span><kbd className="hidden rounded bg-muted px-1.5 py-0.5 text-[10px] sm:inline">⌘ K</kbd></button><Link href="/profile" className="rounded-xl p-2.5 text-muted-foreground hover:bg-muted" aria-label="Learning reminder settings" data-testid="button-notifications"><Bell size={18} /></Link><Link href="/profile" className="grid h-9 w-9 place-items-center rounded-full bg-[#e8bd72] text-sm font-semibold text-[#173b40]" data-testid="link-avatar">{initials(state.name)}</Link></div></header><div className="mx-auto max-w-[1240px] px-4 py-7 sm:px-8 lg:py-10">{children}</div></main>
    <div className="fixed bottom-4 left-1/2 z-30 flex -translate-x-1/2 gap-1 rounded-2xl border border-border bg-card/95 p-1.5 shadow-lg backdrop-blur md:hidden">{nav.map(item => { const Icon = item.icon; return <Link key={item.href} href={item.href} className={`rounded-xl p-3 ${location === item.href ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`} data-testid={`mobile-link-${item.label}`}><Icon size={18} /></Link>})}</div>
    <AskFinova open={chatOpen} onToggle={() => setChatOpen(!chatOpen)} />
    {searchOpen && <GlobalSearch onClose={() => setSearchOpen(false)} />}
  </div>;
}

function GlobalSearch({ onClose }: { onClose: () => void }) {
  const [q, setQ] = useState('');
  const results = useMemo(() => { const query = q.toLowerCase(); if (!query) return []; return [...lessons.map(x => ({ type: 'Lesson', title: x.title, href: `/lesson/${x.id}` })), ...glossary.map(x => ({ type: 'Definition', title: x.term, href: '/glossary' })), { type: 'Simulation', title: 'First Paycheck simulation', href: '/practice/first-paycheck' }].filter(x => x.title.toLowerCase().includes(query)).slice(0, 6); }, [q]);
  return <div className="fixed inset-0 z-50 bg-[#173b40]/30 p-4 backdrop-blur-sm" onClick={onClose}><div className="mx-auto mt-[10vh] max-w-xl overflow-hidden rounded-3xl border border-border bg-card shadow-2xl" onClick={e => e.stopPropagation()}><div className="flex items-center gap-3 border-b border-border px-5 py-4"><Search size={20} className="text-muted-foreground" /><input autoFocus value={q} onChange={e => setQ(e.target.value)} placeholder="Search lessons, definitions, simulations…" className="flex-1 bg-transparent text-base outline-none" data-testid="input-global-search" /><button onClick={onClose} aria-label="Close search" data-testid="button-close-search"><X size={18} /></button></div><div className="p-3">{results.length ? results.map(result => <Link key={result.title} href={result.href} onClick={onClose} className="flex items-center justify-between rounded-xl px-3 py-3 hover:bg-muted" data-testid={`search-result-${result.title.replaceAll(' ', '-').toLowerCase()}`}><span>{result.title}</span><span className="text-xs text-muted-foreground">{result.type}</span></Link>) : <p className="px-3 py-8 text-center text-sm text-muted-foreground">{q ? 'No matches yet. Try “Roth” or “emergency”.' : 'Type to search your learning library.'}</p>}</div></div></div>;
}

function AskFinova({ open, onToggle }: { open: boolean; onToggle: () => void }) {
  const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState('');
  const responses: Record<string, string> = { 'roth ira': 'A Roth IRA is a retirement account that can allow eligible contributions to grow tax-free under current rules. Finova can help you learn the language; it cannot tell you what to invest in.', 'saving vs investing': 'Saving is usually for near-term needs and a buffer. Investing is generally for longer horizons and can rise and fall. Many people learn about both, in that order.', '401k match': 'A 401(k) match is an employer contribution tied to yours. Read your workplace plan details carefully—Finova can explain the concept, not recommend a contribution.', '401(k) match': 'A 401(k) match is an employer contribution tied to yours. Read your workplace plan details carefully—Finova can explain the concept, not recommend a contribution.', 'emergency savings': 'An emergency fund is a flexible cushion for surprises. Starting with a small, consistent amount is a practical learning step.' };
  const ask = () => { const found = Object.keys(responses).find(k => question.toLowerCase().includes(k)); setAnswer(found ? responses[found] : 'Try asking about Roth IRA, saving vs investing, a 401(k) match, or emergency savings.'); };
  return <><button onClick={onToggle} className="fixed bottom-5 right-5 z-40 flex items-center gap-2 rounded-full bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground shadow-lg transition-transform hover:-translate-y-0.5 md:bottom-7 md:right-8" data-testid="button-ask-finova"><MessageCircle size={18} />Ask Finova</button>{open && <div className="fixed bottom-20 right-4 z-40 w-[calc(100vw-2rem)] max-w-sm overflow-hidden rounded-3xl border border-border bg-card shadow-2xl md:right-8"><div className="bg-[#173b40] p-5 text-[#f6e9cb]"><div className="flex items-center justify-between"><div><p className="font-semibold">Ask Finova</p><p className="mt-1 text-xs text-[#f6e9cb]/70">Education, not individualized advice</p></div><button onClick={onToggle} aria-label="Close Ask Finova" data-testid="button-close-ask-finova"><X size={18} /></button></div></div><div className="space-y-3 p-4">{answer && <div className="rounded-2xl bg-secondary/50 p-3 text-sm leading-relaxed">{answer}</div>}<div className="flex gap-2"><input value={question} onChange={e => setQuestion(e.target.value)} onKeyDown={e => e.key === 'Enter' && ask()} placeholder="Ask a money question…" className="min-w-0 flex-1 rounded-xl border border-input bg-background px-3 py-2 text-sm outline-none" data-testid="input-ask-finova" /><button onClick={ask} className="rounded-xl bg-primary px-3 text-primary-foreground" data-testid="button-submit-ask"><Search size={16} /></button></div></div></div>}</>;
}